export const randomWordAPI = async () => {
  let wordsArray: string[] = [];

  const character =
    allCharacters[Math.floor(Math.random() * allCharacters.length)];
  wordsArray.push(character);
  const mood = allMoods[Math.floor(Math.random() * allMoods.length)];
  wordsArray.push(mood);

  return wordsArray;
};

const allCharacters = [
  'Super-Man',
  'Batman',
  'Harry Potter',
  'Iron Man',
  'Spider-Man',
  'Wonder Woman',
  'Gandalf',
  'Captain America',
  'Hercules',
  'Pegasus',
  'Mickey Mouse',
  'James Bond',
  'Bugs Bunny',
  'Peter Pan',
  'Indiana Jones',
  'Rocky Balboa',
  'Vito Corleone',
  'Homer Simpson',
  'King Kong',
  'Fredy Krueger',
  'Goku',

  // animals
  'Dog',
  'Cat',
  'Horse',
  'Mouse',
  'Hypo',
  'Lion',
  'Tiger',
  'Elephant',
  'Wolf',
  'Dolpin',
  'Octopus',
  'Shark',
  'Turtle',
  'Coyote',
  'Elk',
  'Snake',
  'Crocodile',
  'Racoon',
  'Bear',
  'Monkey',
  'Seahorse',
  'Rabbit',
  'Parrot',
  'Mouse',

  'Astronaut',
  'Artist',
  'Soccer Player',
  'Chef',
  'Detective',
  'Rock Star',
  'Pilot',
  'Scientist',
  'Teacher',
  'Doctor',
  'Soldier',
  'Police officer',
  'Firefighter',
  'Business man',
  'Veterinarian',
  'Plumber',
  'Dancer'
];

const allMoods = [
  'happy',
  'sad',
  'angry',
  'excited',
  'worried',
  'anxious',
  'scared',
  'mad',
  'bitter',
  'frustrated',
  'horrified',
  'offended',
  'surprised',
  'astonished',
  'relaxed',
  'pleased',
  'afraid',
  'depressed',
  'bored',
  'tired',
  'distracted',
  'interested',
  'pride',
  'guilt',
  'shame',
  'grief',
  'embarrased',
  'jelous',
  'agonizing',
  'loving',
  'arrogant',
  'cheerful',
  'confident',
  'confused',
  'demoralized',
  'suspicious',
  'vengeful',
  'weak',
  'strong',
  'silly',
  'sexy',
  'seductive'
];
